# Generated by Django 4.1.5 on 2023-01-31 01:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("entities", "0002_alter_tenant_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tenantuser",
            unique_together={("tenant", "user")},
        ),
    ]
