# Generated by Django 4.1.5 on 2023-02-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0003_alter_tenantuser_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="transaction",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="transaction",
            name="split",
            field=models.BooleanField(default=False),
        ),
    ]
