# Generated by Django 4.1.5 on 2023-02-02 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0004_alter_transaction_unique_together_transaction_split"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="split_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="entities.transaction",
            ),
        ),
    ]
