# Generated by Django 4.1.5 on 2023-02-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0005_transaction_split_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="stack",
            name="goal",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
