# Generated by Django 4.1.5 on 2023-02-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transfer_id",
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
