# Generated by Django 4.1.5 on 2023-02-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0002_transaction_transfer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="stack",
            name="position",
            field=models.IntegerField(default=0),
        ),
    ]
