# Generated by Django 4.1.5 on 2023-02-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0004_stackbudget"),
    ]

    operations = [
        migrations.AddField(
            model_name="stack",
            name="budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.DeleteModel(
            name="StackBudget",
        ),
    ]
